# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

University.create(name: "SNU")
University.create(name: "Harvard")
University.create(name: "Yale")
University.create(name: "Princetorn")
University.create(name: "Stanford")
University.create(name: "MIT")

Professor.create(name: "ucheol2")
Professor.create(name: "JacktheLee")
Professor.create(name: "miniddong")
Professor.create(name: "pjhjohn")
Professor.create(name: "CallMeJustNam")

Student.create(university_id: 1, name: "유진영", student_number: "2010-12312", major: "cba")
Student.create(university_id: 1, name: "송재윤", student_number: "2016-10274", major: "cba")
Student.create(university_id: 1, name: "서수빈", student_number: "2010-14797", major: "eng")
Student.create(university_id: 2, name: "김근영", student_number: "2014-17599", major: "cls")
Student.create(university_id: 2, name: "이현민", student_number: "2012-11729", major: "social")
Student.create(university_id: 2, name: "이두희", student_number: "2003-12497", major: "eng")
Student.create(university_id: 3, name: "손병찬", student_number: "2013-15790", major: "eng")
Student.create(university_id: 3, name: "김태완", student_number: "2014-16759", major: "eng")
Student.create(university_id: 3, name: "임정건", student_number: "2007-17952", major: "eng")
Student.create(university_id: 4, name: "김권봉", student_number: "2007-17509", major: "art")
Student.create(university_id: 4, name: "송기서", student_number: "2012-15725", major: "art")
Student.create(university_id: 4, name: "윤현영", student_number: "2014-17538", major: "cls")
Student.create(university_id: 5, name: "서동욱", student_number: "2011-19752", major: "eng")
Student.create(university_id: 5, name: "박승환", student_number: "2010-12098", major: "eng")
Student.create(university_id: 5, name: "김경도", student_number: "2011-18357", major: "eng")

LectureEvaluation.create(student_id: 1, professor_id: 1, grade: 7, lecture_name: "model_advanced")
LectureEvaluation.create(student_id: 1, professor_id: 2, grade: 6, lecture_name: "JacktheLee's lecture")
LectureEvaluation.create(student_id: 2, professor_id: 3, grade: 7, lecture_name: "git")
LectureEvaluation.create(student_id: 3, professor_id: 3, grade: 10, lecture_name: "git")
LectureEvaluation.create(student_id: 4, professor_id: 4, grade: 8, lecture_name: "asset_pipeline")
LectureEvaluation.create(student_id: 5, professor_id: 1, grade: 4, lecture_name: "model_advanced")
LectureEvaluation.create(student_id: 5, professor_id: 4, grade: 0, lecture_name: "asset_pipeline")
LectureEvaluation.create(student_id: 5, professor_id: 5, grade: 1, lecture_name: "foundation_of_rails")

Book.create(title: "Perfect Ruby on Rails", author: "Yamada Yoshihiro")
Book.create(title: "Brave New World", author: "Aldous Huxley")
Book.create(title: "Guns, Germs and Steel", author: "Jared Diamond")
Book.create(title: "The Selfish Gene", author: "Richard Dawkins")

Page.create(book_id: 1, content: "Perfect")
Page.create(book_id: 1, content: "Ruby")
Page.create(book_id: 1, content: "on")
Page.create(book_id: 1, content: "Rails")
Page.create(book_id: 2, content: "Brave")
Page.create(book_id: 2, content: "New")
Page.create(book_id: 2, content: "World")
Page.create(book_id: 3, content: "Guns")
Page.create(book_id: 3, content: "Germs")
Page.create(book_id: 3, content: "and")
Page.create(book_id: 3, content: "Steel")
Page.create(book_id: 4, content: "The")
Page.create(book_id: 4, content: "Selfish")
Page.create(book_id: 4, content: "Gene")

Group.create(name: "Hello")
Group.create(name: "World")

Member.create(team_id: 1, name: "유진영")
Member.create(team_id: 1, name: "송재윤")
Member.create(team_id: 1, name: "서수빈")
Member.create(team_id: 1, name: "김근영")
Member.create(team_id: 1, name: "이현민")
Member.create(team_id: 1, name: "이두희")
Member.create(team_id: 1, name: "손병찬")
Member.create(team_id: 2, name: "김태완")
Member.create(team_id: 2, name: "임정건")
Member.create(team_id: 2, name: "김권봉")
Member.create(team_id: 2, name: "송기서")
Member.create(team_id: 2, name: "윤현영")
Member.create(team_id: 2, name: "서동욱")
Member.create(team_id: 2, name: "박승환")
Member.create(team_id: 2, name: "김경도")

User.create(group_id: 1, seller_id: 4, name: "유진영")
User.create(group_id: 1, seller_id: 14, name: "송재윤")
User.create(group_id: 1, seller_id: 12, name: "서수빈")
User.create(group_id: 1, seller_id: 7, name: "김근영")
User.create(group_id: 1, seller_id: 5, name: "이현민")
User.create(group_id: 1, seller_id: 12, name: "이두희")
User.create(group_id: 1, seller_id: 14, name: "손병찬")
User.create(group_id: 2, seller_id: 1, name: "김태완")
User.create(group_id: 2, seller_id: 7, name: "임정건")
User.create(group_id: 2, seller_id: 4, name: "김권봉")
User.create(group_id: 2, seller_id: 5, name: "송기서")
User.create(group_id: 2, seller_id: 14, name: "윤현영")
User.create(group_id: 2, seller_id: 12, name: "서동욱")
User.create(group_id: 2, seller_id: 4, name: "박승환")
User.create(group_id: 2, seller_id: 1, name: "김경도")
